---
version: '3'
services:
    mvn:
        build:
            context: ./docker
            dockerfile: dockerfile
        volumes:
          - './app :/tmp/app/'
    tomcat:
        build:
            context: ./docker
            dockerfile: tc.dockerfile
        ports:
           - '8880:80'
           - '442:443'
        volumes:
            - './app:/var/www/html'



