---
version: '3'
services:
    mvn:
        build:
            context: ./HW7/docker
            dockerfile: dockerfile
        volumes:
          - './HW7/app :/tmp/app/'
    tomcat:
        image: tomcat:9.0.105-jre11-temurin-noble
#      build:
#            context: ./docker
#            dockerfile: tc.dockerfile
        ports:
           - '8880:80'
           - '442:443'
        volumes:
            - './HW7/app:/usr/local/tomcat/webapps'
        depends_on:
            - mvn




