FROM ubuntu:18.04
RUN apt update
RUN apt install default-jdk -y
RUN apt install maven -y
RUN apt install git -y
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /tmp/boxfuse-sample-java-war-hello
RUN cd /tmp/boxfuse-sample-java-war-hello && \
    mvn package
RUN cd /tmp/boxfuse-sample-java-war-hello/target
WORKDIR /tmp/app/
RUN cp /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war /tmp/app/